### ISSUE TITLE
Installation guide makes reference to a bentoV2 that is otherwise not mentioned

### ISSUE THREAD

**Issue by andrewpatto** [bento-platform/bento#248]
Am just following the installation guide as a naive user - and it refers to the `bentoV2` folder. I am presuming this means the root of the checked out `bento` repository, but probably was left with a legacy folder name.

Start of section (2) in `docs/installation.md`.

**Comment by davidlougheed** [comment]
Hi @andrewpatto, thank you for reporting this and sorry for the delay in addressing it. I've just fixed this typo for the docs in our upcoming v17 release.
