### ISSUE TITLE
bentoctl init-all failing on fresh check-out due to downstream requests issue

### ISSUE THREAD

**Issue by andrewpatto** [bento-platform/bento#249]
There appears to be an issue with downstream `requests` - that makes the `bentoctl` scripsts not work out of the box.

```
File "bento/env/lib/python3.12/site-packages/requests/adapters.py", line 559, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Not supported URL scheme http+docker
```

I fixed with a pin of requests to 2.31, `pip install requests==2.31`, but there are better long term solutions discussed here.

See https://github.com/docker/docker-py/issues/3256

**Comment by davidlougheed** [comment]
this was fixed by 9a04783719c2aa9a2d0008dd37f5e7d4230bf45d in v16, thank you for the report.
